---
title: "plik-pomocniczy"
output: html_document
---

```{r}
library(devtools)
library(usethis)
```

```{r}
#Utworzono plik z licencja
usethis::use_mit_license()
```

```{r}
#Tworzenie pierwszej funkcji
usethis::use_r("skaluj_przepis")
```

```{r}
#Robocze ładowanie pakietu
devtools::load_all()
```

```{r}
#Robocze testowanie pakietu
przepis <- data.frame(
  skladnik = c("maka", "cukier", "jajka"),
  ilosc = c(300, 100, 2),
  jednostka = c("g", "g", "szt.")
)

skaluj_przepis(przepis, porcje_bazowe = 4, porcje_docelowe = 5)
```

```{r}
#Utowrzenie pliku z pomoca
devtools::document()
```

```{r}
#Tworzenie drugiej funkcji
usethis::use_r("przelicz_miare")
```

```{r}
devtools::load_all()
```

```{r}
przelicz_miare("maka", 350, "szklanka")
```

```{r}
devtools::document()
```

```{r}
#Tworzenie trzeciej funkcji
usethis::use_r("przelicz_na_gramy")
```

```{r}
devtools::document()
```

```{r}
#wstepny test
przelicz_na_gramy("cukier", 3, "lyzka")
```

```{r}
#Tworzenie przykladowego zbioru danych
usethis::use_data_raw("przepisy_przykladowe")
```

```{r}
#Wstepny test zbioru danych
skaluj_przepis(
  przepisy_przykladowe[przepisy_przykladowe$przepis == "naleśniki", ],
  porcje_bazowe = 4,
  porcje_docelowe = 5
)
```

```{r}
#Tworzenie helpa dla danych
usethis::use_r("dane")
```

```{r}
#Tworzenie drugiego przykladowego zbioru danych
usethis::use_data_raw("przepisy_w_miarach_kuchennych")
```

```{r}
#Wstepne testowanie drugiego zbioru danych
owsianka <- przepisy_w_miarach_kuchennych[
  przepisy_w_miarach_kuchennych$przepis == "owsianka_kakaowa", 
]
owsianka
wynik_owsianka <- do.call(
  rbind,
  mapply(
    przelicz_na_gramy,
    produkt = owsianka$skladnik,
    ilosc = owsianka$ilosc,
    jednostka = owsianka$jednostka,
    SIMPLIFY = FALSE
  )
)

wynik_owsianka
```

```{r}
#Tworzenie folderu do testow
usethis::use_testthat()
```

```{r}
#Tworzenie pliku z testami
usethis::use_test("funkcje")
```

```{r}
devtools::test()
```

